Hi, this is the chat. If you have something to say, do it here.

I'm feeling stuck on the login terminal. Try running it to figure out what is wrong.

my OTHER terminal, which you, dad, are the only one who has seen until 7/1/19, is acting up. the error is:

Traceback (most recent call last):
  File "/home/pi/Documents/programming/terminal.py", line 57, in <module>
    command()
  File "/home/pi/Documents/programming/terminal.py", line 8, in command
    inputCommand = input(username + "@pythonterminal:~ $ ")
UnboundLocalError: local variable 'username' referenced before assignment


I declare 'username' before I call command().
